<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

		$countries = array(
			array('name' => 'Afghanistan',  'code' => '93'),
            array('name' => 'Albania',  'code' => '355'),
            array('name' => 'Algeria',  'code' => '213'),
            array('name' => 'American Samoa',  'code' => '1684'),
            array('name' => 'Andorra',   'code' => '376'),
            array('name' => 'Angola',   'code' => '244'),
            array('name' => 'Anguilla',  'code' => '1264'),
            array('name' => 'Antarctica', 'code' => '0'),
            array('name' => 'Antigua and Barbuda',  'code' => '1268'),
            array('name' => 'Argentina',  'code' => '54'),
            array('name' => 'Armenia',  'code' => '374'),
            array('name' => 'Aruba',  'code' => '297'),
            array('name' => 'Australia',  'code' => '61'),
            array('name' => 'Austria',  'code' => '43'),
            array('name' => 'Azerbaijan',  'code' => '994'),
            array('name' => 'Bahamas',  'code' => '1242'),
            array('name' => 'Bahrain',  'code' => '973'),
            array('name' => 'Bangladesh',  'code' => '880'),
            array('name' => 'Barbados',  'code' => '1246'),
            array('name' => 'Belarus',  'code' => '375'),
            array('name' => 'Belgium',  'code' => '32'),
            array('name' => 'Belize',  'code' => '501'),
            array('name' => 'Benin',  'code' => '229'),
            array('name' => 'Bermuda',  'code' => '1441'),
            array('name' => 'Bhutan',  'code' => '975'),
            array('name' => 'Bolivia',  'code' => '591'),
            array('name' => 'Bosnia and Herzegovina',  'code' => '387'),
            array('name' => 'Botswana',  'code' => '267'),
            array('name' => 'Bouvet Island','code' => '0'),
            array('name' => 'Brazil',   'code' => '55'),
            array('name' => 'British Indian Ocean Territory', 'code' => '246'),
            array('name' => 'Brunei Darussalam',   'code' => '673'),
            array('name' => 'Bulgaria',  'code' => '359'),
            array('name' => 'Burkina Faso',  'code' => '226'),
            array('name' => 'Burundi',  'code' => '257'),
            array('name' => 'Cambodia',  'code' => '855'),
            array('name' => 'Cameroon',  'code' => '237'),
            array('name' => 'Canada',  'code' => '1'),
            array('name' => 'Cape Verde',  'code' => '238'),
            array('name' => 'Cayman Islands',  'code' => '1345'),
            array('name' => 'Central African Republic',  'code' => '236'),
            array('name' => 'Chad',  'code' => '235'),
            array('name' => 'Chile',  'code' => '56'),
            array('name' => 'China',  'code' => '86'),
            array('name' => 'Christmas Island', 'code' => '61'),
            array('name' => 'Cocos (Keeling) Islands','code' => '672'),
            array('name' => 'Colombia',  'code' => '57'),
            array('name' => 'Comoros',  'code' => '269'),
            array('name' => 'Congo',  'code' => '242'),
            array('name' => 'Congo, the Democratic Republic of the',  'code' => '242'),
            array('name' => 'Cook Islands',  'code' => '682'),
            array('name' => 'Costa Rica',  'code' => '506'),
            array('name' => 'Cote D\'Ivoire',  'code' => '225'),
            array('name' => 'Croatia',  'code' => '385'),
            array('name' => 'Cuba',  'code' => '53'),
            array('name' => 'Cyprus',  'code' => '357'),
            array('name' => 'Czech Republic',  'code' => '420'),
            array('name' => 'Denmark',  'code' => '45'),
            array('name' => 'Djibouti',  'code' => '253'),
            array('name' => 'Dominica',  'code' => '1767'),
            array('name' => 'Dominican Republic',  'code' => '1809'),
            array('name' => 'Ecuador',  'code' => '593'),
            array('name' => 'Egypt',  'code' => '20'),
            array('name' => 'El Salvador',  'code' => '503'),
            array('name' => 'Equatorial Guinea',  'code' => '240'),
            array('name' => 'Eritrea',  'code' => '291'),
            array('name' => 'Estonia',  'code' => '372'),
            array('name' => 'Ethiopia',  'code' => '251'),
            array('name' => 'Falkland Islands (Malvinas)',  'code' => '500'),
            array('name' => 'Faroe Islands',  'code' => '298'),
            array('name' => 'Fiji',  'code' => '679'),
            array('name' => 'Finland',  'code' => '358'),
            array('name' => 'France',  'code' => '33'),
            array('name' => 'French Guiana',  'code' => '594'),
            array('name' => 'French Polynesia',  'code' => '689'),
            array('name' => 'French Southern Territories', 'code' => '0'),
            array('name' => 'Gabon',  'code' => '241'),
            array('name' => 'Gambia',  'code' => '220'),
            array('name' => 'Georgia',  'code' => '995'),
            array('name' => 'Germany',  'code' => '49'),
            array('name' => 'Ghana',  'code' => '233'),
            array('name' => 'Gibraltar',  'code' => '350'),
            array('name' => 'Greece',  'code' => '30'),
            array('name' => 'Greenland',  'code' => '299'),
            array('name' => 'Grenada',  'code' => '1473'),
            array('name' => 'Guadeloupe',  'code' => '590'),
            array('name' => 'Guam',  'code' => '1671'),
            array('name' => 'Guatemala',  'code' => '502'),
            array('name' => 'Guinea',  'code' => '224'),
            array('name' => 'Guinea-Bissau',  'code' => '245'),
            array('name' => 'Guyana',  'code' => '592'),
            array('name' => 'Haiti',  'code' => '509'),
            array('name' => 'Heard Island and Mcdonald Islands', 'code' => '0'),
            array('name' => 'Holy See (Vatican City State)',  'code' => '39'),
            array('name' => 'Honduras',  'code' => '504'),
            array('name' => 'Hong Kong',  'code' => '852'),
            array('name' => 'Hungary',  'code' => '36'),
            array('name' => 'Iceland',  'code' => '354'),
            array('name' => 'India',  'code' => '91'),


            // Records 100-199 (Indonesia to Spain)

            array('name' => 'Indonesia',  'code' => '62'),
            array('name' => 'Iran, Islamic Republic of',  'code' => '98'),
            array('name' => 'Iraq',  'code' => '964'),
            array('name' => 'Ireland',  'code' => '353'),
            array('name' => 'Israel',  'code' => '972'),
            array('name' => 'Italy',  'code' => '39'),
            array('name' => 'Jamaica',  'code' => '1876'),
            array('name' => 'Japan',  'code' => '81'),
            array('name' => 'Jordan',  'code' => '962'),
            array('name' => 'Kazakhstan',  'code' => '7'),
            array('name' => 'Kenya',  'code' => '254'),
            array('name' => 'Kiribati',  'code' => '686'),
            array('name' => 'Korea, Democratic People\'s Republic of',  'code' => '850'),
            array('name' => 'Korea, Republic of',  'code' => '82'),
            array('name' => 'Kuwait',  'code' => '965'),
            array('name' => 'Kyrgyzstan',  'code' => '996'),
            array('name' => 'Lao People\'s Democratic Republic',  'code' => '856'),
            array('name' => 'Latvia',  'code' => '371'),
            array('name' => 'Lebanon',  'code' => '961'),
            array('name' => 'Lesotho',  'code' => '266'),
            array('name' => 'Liberia',  'code' => '231'),
            array('name' => 'Libyan Arab Jamahiriya',  'code' => '218'),
            array('name' => 'Liechtenstein',  'code' => '423'),
            array('name' => 'Lithuania',  'code' => '370'),
            array('name' => 'Luxembourg',  'code' => '352'),
            array('name' => 'Macao',  'code' => '853'),
            array('name' => 'Macedonia, the Former Yugoslav Republic of',  'code' => '389'),
            array('name' => 'Madagascar',  'code' => '261'),
            array('name' => 'Malawi',  'code' => '265'),
            array('name' => 'Malaysia',  'code' => '60'),
            array('name' => 'Maldives',  'code' => '960'),
            array('name' => 'Mali',  'code' => '223'),
            array('name' => 'Malta',  'code' => '356'),
            array('name' => 'Marshall Islands',  'code' => '692'),
            array('name' => 'Martinique',  'code' => '596'),
            array('name' => 'Mauritania',  'code' => '222'),
            array('name' => 'Mauritius',  'code' => '230'),
            array('name' => 'Mayotte', 'code' => '269'),
            array('name' => 'Mexico',  'code' => '52'),
            array('name' => 'Micronesia, Federated States of',  'code' => '691'),
            array('name' => 'Moldova, Republic of',  'code' => '373'),
            array('name' => 'Monaco',  'code' => '377'),
            array('name' => 'Mongolia',  'code' => '976'),
            array('name' => 'Montserrat',  'code' => '1664'),
            array('name' => 'Morocco',  'code' => '212'),
            array('name' => 'Mozambique',  'code' => '258'),
            array('name' => 'Myanmar',  'code' => '95'),
            array('name' => 'Namibia',  'code' => '264'),
            array('name' => 'Nauru',  'code' => '674'),
            array('name' => 'Nepal',  'code' => '977'),
            array('name' => 'Netherlands',  'code' => '31'),
            array('name' => 'Netherlands Antilles',  'code' => '599'),
            array('name' => 'New Caledonia',  'code' => '687'),
            array('name' => 'New Zealand',  'code' => '64'),
            array('name' => 'Nicaragua',  'code' => '505'),
            array('name' => 'Niger',  'code' => '227'),
            array('name' => 'Nigeria',  'code' => '234'),
            array('name' => 'Niue',  'code' => '683'),
            array('name' => 'Norfolk Island',  'code' => '672'),
            array('name' => 'Northern Mariana Islands',  'code' => '1670'),
            array('name' => 'Norway',  'code' => '47'),
            array('name' => 'Oman',  'code' => '968'),
            array('name' => 'Pakistan',  'code' => '92'),
            array('name' => 'Palau',  'code' => '680'),
            array('name' => 'Palestinian Territory, Occupied', 'code' => '970'),
            array('name' => 'Panama', 'code' => '507'),
            array('name' => 'Papua New Guinea', 'code' => '675'),
            array('name' => 'Paraguay', 'code' => '595'),
            array('name' => 'Peru', 'code' => '51'),
            array('name' => 'Philippines', 'code' => '63'),
            array('name' => 'Pitcairn', 'code' => '0'),
            array('name' => 'Poland', 'code' => '48'),
            array('name' => 'Portugal', 'code' => '351'),
            array('name' => 'Puerto Rico', 'code' => '1787'),
            array('name' => 'Qatar', 'code' => '974'),
            array('name' => 'Reunion', 'code' => '262'),
            array('name' => 'Romania', 'code' => '40'),
            array('name' => 'Russian Federation', 'code' => '70'),
            array('name' => 'Rwanda', 'code' => '250'),
            array('name' => 'Saint Helena', 'code' => '290'),
            array('name' => 'Saint Kitts and Nevis', 'code' => '1869'),
            array('name' => 'Saint Lucia', 'code' => '1758'),
            array('name' => 'Saint Pierre and Miquelon', 'code' => '508'),
            array('name' => 'Saint Vincent and the Grenadines', 'code' => '1784'),
            array('name' => 'Samoa', 'code' => '684'),
            array('name' => 'San Marino', 'code' => '378'),
            array('name' => 'Sao Tome and Principe', 'code' => '239'),
            array('name' => 'Saudi Arabia', 'code' => '966'),
            array('name' => 'Senegal', 'code' => '221'),
            array('name' => 'Serbia and Montenegro', 'code' => '381'),
            array('name' => 'Seychelles',  'code' => '248'),
            array('name' => 'Sierra Leone',  'code' => '232'),
            array('name' => 'Singapore',  'code' => '65'),
            array('name' => 'Slovakia',  'code' => '421'),
            array('name' => 'Slovenia',  'code' => '386'),
            array('name' => 'Solomon Islands', 'code' => '677'),
            array('name' => 'Somalia',  'code' => '252'),
            array('name' => 'South Africa',  'code' => '27'),
            array('name' => 'South Georgia and the South Sandwich Islands', 'code' => '0'),
            array('name' => 'Spain',  'code' => '34'),


            // Records 200-253 (Sri Lanka to South Sudan)

            array('name' => 'Sri Lanka',  'code' => '94'),
            array('name' => 'Sudan',  'code' => '249'),
            array('name' => 'Suriname',  'code' => '597'),
            array('name' => 'Svalbard and Jan Mayen',  'code' => '47'),
            array('name' => 'Swaziland',  'code' => '268'),
            array('name' => 'Sweden',  'code' => '46'),
            array('name' => 'Switzerland',  'code' => '41'),
            array('name' => 'Syrian Arab Republic',  'code' => '963'),
            array('name' => 'Taiwan, Province of China',  'code' => '886'),
            array('name' => 'Tajikistan',  'code' => '992'),
            array('name' => 'Tanzania, United Republic of',  'code' => '255'),
            array('name' => 'Thailand',  'code' => '66'),
            array('name' => 'Timor-Leste', 'code' => '670'),
            array('name' => 'Togo',  'code' => '228'),
            array('name' => 'Tokelau',  'code' => '690'),
            array('name' => 'Tonga',  'code' => '676'),
            array('name' => 'Trinidad and Tobago',  'code' => '1868'),
            array('name' => 'Tunisia',  'code' => '216'),
            array('name' => 'Turkey',  'code' => '90'),
            array('name' => 'Turkmenistan',  'code' => '7370'),
            array('name' => 'Turks and Caicos Islands',  'code' => '1649'),
            array('name' => 'Tuvalu',  'code' => '688'),
            array('name' => 'Uganda',  'code' => '256'),
            array('name' => 'Ukraine',  'code' => '380'),
            array('name' => 'United Arab Emirates',  'code' => '971'),
            array('name' => 'United Kingdom',  'code' => '44'),
            array('name' => 'United States',  'code' => '1'),
            array('name' => 'United States Minor Outlying Islands', 'code' => '1'),
            array('name' => 'Uruguay',  'code' => '598'),
            array('name' => 'Uzbekistan',  'code' => '998'),
            array('name' => 'Vanuatu',  'code' => '678'),
            array('name' => 'Venezuela',  'code' => '58'),
            array('name' => 'Viet Nam',  'code' => '84'),
            array('name' => 'Virgin Islands, British', 'code' => '1284'),
            array('name' => 'Virgin Islands, U.S.',  'code' => '1340'),
            array('name' => 'Wallis and Futuna',  'code' => '681'),
            array('name' => 'Western Sahara',  'code' => '212'),
            array('name' => 'Yemen',  'code' => '967'),
            array('name' => 'Zambia',  'code' => '260'),
            array('name' => 'Zimbabwe',  'code' => '263'),
            array('name' => 'Serbia',  'code' => '381'),
            array('name' => 'Asia / Pacific Region', 'code' => '0'),
            array('name' => 'Montenegro', 'code' => '382'),
            array('name' => 'Aland Islands',  'code' => '358'),
            array('name' => 'Bonaire, Sint Eustatius and Saba',  'code' => '599'),
            array('name' => 'Curacao',  'code' => '599'),
            array('name' => 'Guernsey',  'code' => '44'),
            array('name' => 'Isle of Man',  'code' => '44'),
            array('name' => 'Jersey',  'code' => '44'),
            array('name' => 'Kosovo', 'code' => '381'),
            array('name' => 'Saint Barthelemy',  'code' => '590'),
            array('name' => 'Saint Martin',  'code' => '590'),
            array('name' => 'Sint Maarten',  'code' => '1'),
            array('name' => 'South Sudan',  'code' => '211')
		);

		DB::table('countries')->insert($countries);
    }
}
